package de.regelsuche.polynomial;

import de.regelsuche.ast.Expr;
import de.regelsuche.canonical.ExpressionCanonicalizer;
import de.regelsuche.input.InputRequest;
import de.regelsuche.input.InputType;
import de.regelsuche.parse.ExpressionParser;
import de.regelsuche.transform.PolynomialStructureSynthesisOperator;
import de.regelsuche.transform.Transformation;
import java.util.Objects;

/**
 * Classifies a proposed pattern rule as generated by the bounded polynomial
 * theory procedure, so promotion can keep it in a derived cache instead of
 * growing the mathematical kernel.
 */
public final class PolynomialTheorySubsumptionClassifier {
    private final ExpressionParser parser = new ExpressionParser();
    private final ExpressionCanonicalizer canonicalizer =
        new ExpressionCanonicalizer();
    private final PolynomialSemanticView semanticView =
        new PolynomialSemanticView();
    private final PolynomialStructureSynthesisOperator operator =
        new PolynomialStructureSynthesisOperator();

    public Result classify(String leftPattern, String rightPattern) {
        if (leftPattern == null || leftPattern.isBlank()
                || rightPattern == null || rightPattern.isBlank()) {
            return Result.unsupported("PATTERN_IS_BLANK");
        }
        Expr left;
        Expr right;
        try {
            left = parse(leftPattern);
            right = parse(rightPattern);
        } catch (IllegalArgumentException exception) {
            return Result.unsupported("PATTERN_IS_NOT_PARSEABLE");
        }

        PolynomialSemanticView.Result leftView = semanticView.analyze(left);
        PolynomialSemanticView.Result rightView = semanticView.analyze(right);
        if (!leftView.supported() || !rightView.supported()) {
            return Result.unsupported(
                "OUTSIDE_POLYNOMIAL_THEORY_SURFACE:"
                    + leftView.detailCode() + ":" + rightView.detailCode());
        }
        if (!leftView.view().polynomial().canonical().equals(
                rightView.view().polynomial().canonical())) {
            return new Result(
                Status.NOT_EQUIVALENT,
                leftView.view().semanticHash(),
                "",
                "",
                "",
                "POLYNOMIAL_NORMAL_FORMS_DIFFER");
        }

        String targetStructure = canonicalizer.canonicalize(rightPattern);
        for (Transformation candidate : operator.generateCandidates(leftPattern)) {
            if (canonicalizer.canonicalize(candidate.transformedExpression())
                    .equals(targetStructure)) {
                return new Result(
                    Status.SUBSUMED,
                    leftView.view().semanticHash(),
                    PolynomialStructureSynthesisOperator.RULE_ID,
                    candidate.transformedExpression(),
                    candidate.applicationKey(),
                    "THEORY_PROCEDURE_REPRODUCES_TARGET_STRUCTURE");
            }
        }
        return new Result(
            Status.NOT_SUBSUMED,
            leftView.view().semanticHash(),
            PolynomialStructureSynthesisOperator.RULE_ID,
            "",
            "",
            "NO_MATCHING_THEORY_CANDIDATE_WITHIN_BUDGET");
    }

    private Expr parse(String expression) {
        return parser.parse(new InputRequest(InputType.TERM, expression))
            .terms().getFirst();
    }

    public enum Status {
        SUBSUMED,
        NOT_SUBSUMED,
        NOT_EQUIVALENT,
        UNSUPPORTED
    }

    public record Result(
        Status status,
        String sourceSemanticHash,
        String theoryRuleId,
        String matchingCandidate,
        String applicationKey,
        String detailCode
    ) {
        public Result {
            Objects.requireNonNull(status, "status");
            sourceSemanticHash = sourceSemanticHash == null ? "" : sourceSemanticHash;
            theoryRuleId = theoryRuleId == null ? "" : theoryRuleId;
            matchingCandidate = matchingCandidate == null ? "" : matchingCandidate;
            applicationKey = applicationKey == null ? "" : applicationKey;
            detailCode = detailCode == null ? "" : detailCode;
        }

        static Result unsupported(String detailCode) {
            return new Result(
                Status.UNSUPPORTED,
                "",
                "",
                "",
                "",
                detailCode);
        }

        public boolean subsumed() {
            return status == Status.SUBSUMED;
        }
    }
}
