package de.regelsuche.docs;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class GeneratedDiscoveryGalleryContractTest {
    private static final Path README_PATH = Path.of("README.md");
    private static final List<Path> GENERATED_PATHS = List.of(
        Path.of("docs/generated/discovery"),
        Path.of("docs/demo-gallery.md"),
        README_PATH
    );

    @Test
    void generatorReproducesCommittedGalleryByteForByte(
        @TempDir Path temporary
    ) throws IOException {
        Path repository = repositoryRoot();
        Path committedReadme = repository.resolve(README_PATH);
        assertTrue(
            Files.isRegularFile(committedReadme, LinkOption.NOFOLLOW_LINKS),
            "committed README must be a regular file"
        );
        Files.copy(committedReadme, temporary.resolve(README_PATH));

        new DocsDiscoveryGalleryGenerator().generate(temporary);

        for (Path relative : GENERATED_PATHS) {
            Path expected = repository.resolve(relative);
            Path actual = temporary.resolve(relative);
            assertSameTree(expected, actual, relative);
        }
    }

    @Test
    void treeComparisonRejectsMembershipAndByteDrift(
        @TempDir Path temporary
    ) throws IOException {
        Path expected = temporary.resolve("expected");
        Path actual = temporary.resolve("actual");
        Files.createDirectories(expected);
        Files.createDirectories(actual);
        Files.writeString(
            expected.resolve("evidence.json"),
            "expected\n",
            StandardCharsets.UTF_8
        );
        Files.writeString(
            actual.resolve("evidence.json"),
            "changed\n",
            StandardCharsets.UTF_8
        );

        assertThrows(
            AssertionError.class,
            () -> assertSameTree(expected, actual, Path.of("generated"))
        );

        Files.writeString(
            actual.resolve("evidence.json"),
            "expected\n",
            StandardCharsets.UTF_8
        );
        Files.writeString(
            actual.resolve("unexpected.txt"),
            "unexpected\n",
            StandardCharsets.UTF_8
        );
        assertThrows(
            AssertionError.class,
            () -> assertSameTree(expected, actual, Path.of("generated"))
        );
    }

    private static void assertSameTree(
        Path expected,
        Path actual,
        Path displayPath
    ) throws IOException {
        assertFalse(
            Files.isSymbolicLink(expected),
            "committed generated path must not be symbolic: " + displayPath
        );
        assertFalse(
            Files.isSymbolicLink(actual),
            "regenerated path must not be symbolic: " + displayPath
        );

        if (Files.isRegularFile(expected, LinkOption.NOFOLLOW_LINKS)) {
            assertTrue(
                Files.isRegularFile(actual, LinkOption.NOFOLLOW_LINKS),
                "missing regenerated file: " + displayPath
            );
            assertEquals(
                -1L,
                Files.mismatch(expected, actual),
                "regenerated bytes differ: " + displayPath
            );
            return;
        }

        assertTrue(
            Files.isDirectory(expected, LinkOption.NOFOLLOW_LINKS),
            "committed generated path is missing: " + displayPath
        );
        assertTrue(
            Files.isDirectory(actual, LinkOption.NOFOLLOW_LINKS),
            "regenerated directory is missing: " + displayPath
        );

        List<Path> expectedFiles = relativeFiles(expected);
        List<Path> actualFiles = relativeFiles(actual);
        assertEquals(
            expectedFiles,
            actualFiles,
            "regenerated file set differs below " + displayPath
        );
        for (Path relative : expectedFiles) {
            Path expectedFile = expected.resolve(relative);
            Path actualFile = actual.resolve(relative);
            assertFalse(
                Files.isSymbolicLink(expectedFile),
                "committed generated file must not be symbolic: "
                    + displayPath.resolve(relative)
            );
            assertFalse(
                Files.isSymbolicLink(actualFile),
                "regenerated file must not be symbolic: "
                    + displayPath.resolve(relative)
            );
            assertEquals(
                -1L,
                Files.mismatch(expectedFile, actualFile),
                "regenerated bytes differ: "
                    + displayPath.resolve(relative)
            );
        }
    }

    private static List<Path> relativeFiles(Path root) throws IOException {
        try (Stream<Path> paths = Files.walk(root)) {
            return paths
                .filter(path -> !path.equals(root))
                .peek(path -> assertFalse(
                    Files.isSymbolicLink(path),
                    "generated tree must not contain symbolic paths: " + path
                ))
                .filter(path ->
                    Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS))
                .map(root::relativize)
                .sorted()
                .toList();
        }
    }

    private static Path repositoryRoot() {
        String configured = System.getProperty("regelsuche.repositoryRoot");
        if (configured != null && !configured.isBlank()) {
            return Path.of(configured).toAbsolutePath().normalize();
        }
        Path candidate = Path.of(".").toAbsolutePath().normalize();
        for (int index = 0; index < 8 && candidate != null; index++) {
            if (Files.isRegularFile(candidate.resolve("README.md"))
                    && Files.isRegularFile(candidate.resolve(
                        "settings.gradle"))) {
                return candidate;
            }
            candidate = candidate.getParent();
        }
        throw new AssertionError("Could not locate repository root");
    }
}
