package de.regelsuche.proof;

import de.regelsuche.assumption.Assumption;
import de.regelsuche.validation.CandidateProofStatus;
import java.util.List;

/**
 * Generates a Lean 4 lemma skeleton for the equivalence.
 *
 * <p>This bridge is intentionally a "skeleton generator": it produces a Lean
 * theorem of the form
 * <pre>
 *   theorem regelsuche_lemma (a b : ℝ) (h : assumptions) : left = right := by
 *     sorry
 * </pre>
 * and reports {@link CandidateProofStatus#FORMALLY_PROVABLE}. Actually
 * discharging the {@code sorry} requires a Lean toolchain; integrating Lean
 * as a JVM library is out of scope here, but the artifact is suitable to be
 * checked into a Lean project.</p>
 */
public class LeanProofBridge implements ProofBridge {

    @Override
    public ProofAttempt prove(String left, String right, List<Assumption> assumptions) {
        StringBuilder builder = new StringBuilder();
        builder.append("-- Auto-generated by Regelsuche LeanProofBridge\n");
        builder.append("-- left  : ").append(left).append('\n');
        builder.append("-- right : ").append(right).append('\n');
        for (Assumption assumption : assumptions) {
            builder.append("-- assume ").append(assumption).append('\n');
        }
        builder.append("theorem regelsuche_lemma");
        for (int i = 0; i < assumptions.size(); i++) {
            builder.append(" (h").append(i).append(" : ").append(toLeanProp(assumptions.get(i))).append(')');
        }
        builder.append(" : ").append(toLeanExpr(left)).append(" = ").append(toLeanExpr(right)).append(" := by\n");
        builder.append("  sorry\n");
        return new ProofAttempt(CandidateProofStatus.FORMALLY_PROVABLE, builder.toString(), "lean4");
    }

    private String toLeanExpr(String expression) {
        return expression
            .replace("*", " * ")
            .replace("^", " ^ ");
    }

    private String toLeanProp(Assumption assumption) {
        return switch (assumption.kind()) {
            case NON_ZERO -> assumption.symbols().isEmpty()
                ? assumption.expression()
                : assumption.symbols().get(0) + " ≠ 0";
            case POSITIVE -> assumption.symbols().isEmpty()
                ? assumption.expression()
                : assumption.symbols().get(0) + " > 0";
            case NON_NEGATIVE -> assumption.symbols().isEmpty()
                ? assumption.expression()
                : assumption.symbols().get(0) + " ≥ 0";
            case DOMAIN, CUSTOM -> assumption.expression();
        };
    }
}
