package de.regelsuche.proof;

import de.regelsuche.assumption.Assumption;
import de.regelsuche.mining.CandidateProofStatus;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Generates an SMT-LIB 2 script that asks the solver to prove the equivalence
 * (i.e. that the negation is unsatisfiable).
 *
 * <p>As with {@link LeanProofBridge}, the bridge only emits the script and
 * reports {@link CandidateProofStatus#FORMALLY_PROVABLE}; actually running
 * Z3/CVC5 to discharge the obligation is out of scope of this module.</p>
 */
public class SmtProofBridge implements ProofBridge {
    private static final Pattern IDENT = Pattern.compile("[a-zA-Z_][a-zA-Z0-9_]*");
    private static final Set<String> KNOWN_FUNCTIONS = Set.of(
        "sin", "cos", "tan", "log", "ln", "sqrt", "exp", "abs", "pow"
    );

    @Override
    public ProofAttempt prove(String left, String right, List<Assumption> assumptions) {
        Set<String> identifiers = collectIdentifiers(left, right, assumptions);
        Set<String> functions = new LinkedHashSet<>();
        for (String name : identifiers) {
            if (KNOWN_FUNCTIONS.contains(name)) {
                functions.add(name);
            }
        }
        identifiers.removeAll(KNOWN_FUNCTIONS);
        StringBuilder builder = new StringBuilder();
        builder.append("; Auto-generated by Regelsuche SmtProofBridge\n");
        builder.append("; left  : ").append(left).append('\n');
        builder.append("; right : ").append(right).append('\n');
        builder.append("(set-logic UFNRA)\n");
        for (String function : functions) {
            builder.append("(declare-fun ").append(function).append(" (Real) Real)\n");
        }
        for (String identifier : identifiers) {
            builder.append("(declare-const ").append(identifier).append(" Real)\n");
        }
        for (Assumption assumption : assumptions) {
            builder.append("(assert ").append(toSmt(assumption)).append(")\n");
        }
        builder.append("(assert (not (= ").append(toSmtExpr(left)).append(' ').append(toSmtExpr(right)).append(")))\n");
        builder.append("(check-sat)\n");
        builder.append("(exit)\n");
        return new ProofAttempt(CandidateProofStatus.FORMALLY_PROVABLE, builder.toString(), "smtlib2");
    }

    private String toSmt(Assumption assumption) {
        return switch (assumption.kind()) {
            case NON_ZERO -> "(distinct " + renderTerm(assumption) + " 0)";
            case POSITIVE -> "(> " + renderTerm(assumption) + " 0)";
            case NON_NEGATIVE -> "(>= " + renderTerm(assumption) + " 0)";
            case DOMAIN, CUSTOM -> "(! true :named " + sanitize(assumption.expression()) + ")";
        };
    }

    /**
     * Render the assumption's underlying term as an SMT-LIB prefix expression.
     * Prefers the structured {@code symbols} list if available; otherwise
     * strips a trailing comparison operator from {@code expression} (e.g.
     * {@code "cos(x) != 0"} → {@code cos(x)}) and parses the remainder.
     */
    private String renderTerm(Assumption assumption) {
        String raw = assumption.symbols().isEmpty()
            ? stripComparisonSuffix(assumption.expression())
            : assumption.symbols().get(0);
        return toSmtExpr(raw);
    }

    private String stripComparisonSuffix(String expression) {
        String text = expression;
        int idx = indexOfOperator(text, "!=");
        if (idx < 0) idx = indexOfOperator(text, ">=");
        if (idx < 0) idx = indexOfOperator(text, "<=");
        if (idx < 0) idx = indexOfOperator(text, ">");
        if (idx < 0) idx = indexOfOperator(text, "<");
        if (idx < 0) idx = indexOfOperator(text, "=");
        return idx < 0 ? text : text.substring(0, idx).trim();
    }

    private int indexOfOperator(String text, String op) {
        return text.indexOf(op);
    }

    private String sanitize(String expression) {
        StringBuilder sanitized = new StringBuilder(expression.length());
        for (int i = 0; i < expression.length(); i++) {
            char c = expression.charAt(i);
            sanitized.append(Character.isLetterOrDigit(c) || c == '_' ? c : '_');
        }
        return sanitized.toString();
    }

    private Set<String> collectIdentifiers(String left, String right, List<Assumption> assumptions) {
        Set<String> identifiers = new LinkedHashSet<>();
        collectFrom(left, identifiers);
        collectFrom(right, identifiers);
        for (Assumption assumption : assumptions) {
            assumption.symbols().forEach(symbol -> collectFrom(symbol, identifiers));
        }
        return identifiers;
    }

    private void collectFrom(String text, Set<String> identifiers) {
        Matcher matcher = IDENT.matcher(text);
        while (matcher.find()) {
            String match = matcher.group();
            if (!isNumeric(match)) {
                identifiers.add(match);
            }
        }
    }

    private boolean isNumeric(String value) {
        return value.matches("\\d+(\\.\\d+)?");
    }

    private String toSmtExpr(String expression) {
        // Convert infix arithmetic to SMT prefix expressions using a small
        // recursive descent parser. Supports +, -, *, /, ^ (translated to a
        // dummy "pow" function for SMT-LIB compatibility) and unary minus.
        return new InfixToSmt(expression).parse();
    }

    private static final class InfixToSmt {
        private final String source;
        private int position;

        private InfixToSmt(String source) {
            this.source = source;
            this.position = 0;
        }

        String parse() {
            String result = parseExpression();
            skipWhitespace();
            if (position < source.length()) {
                // Bail out: emit the raw expression as a token so the SMT
                // solver complains visibly instead of silently producing
                // wrong output.
                return "|" + source + "|";
            }
            return result;
        }

        private String parseExpression() {
            String left = parseTerm();
            while (true) {
                skipWhitespace();
                if (position >= source.length()) {
                    return left;
                }
                char c = source.charAt(position);
                if (c == '+' || c == '-') {
                    position++;
                    String right = parseTerm();
                    left = "(" + (c == '+' ? "+" : "-") + " " + left + " " + right + ")";
                } else {
                    return left;
                }
            }
        }

        private String parseTerm() {
            String left = parseFactor();
            while (true) {
                skipWhitespace();
                if (position >= source.length()) {
                    return left;
                }
                char c = source.charAt(position);
                if (c == '*' || c == '/') {
                    position++;
                    String right = parseFactor();
                    left = "(" + (c == '*' ? "*" : "/") + " " + left + " " + right + ")";
                } else {
                    return left;
                }
            }
        }

        private String parseFactor() {
            skipWhitespace();
            if (position < source.length() && source.charAt(position) == '-') {
                position++;
                String operand = parseFactor();
                return "(- " + operand + ")";
            }
            String base = parsePrimary();
            skipWhitespace();
            if (position < source.length() && source.charAt(position) == '^') {
                position++;
                String exponent = parseFactor();
                return "(pow " + base + " " + exponent + ")";
            }
            return base;
        }

        private String parsePrimary() {
            skipWhitespace();
            if (position >= source.length()) {
                return "?";
            }
            char c = source.charAt(position);
            if (c == '(') {
                position++;
                String inner = parseExpression();
                skipWhitespace();
                if (position < source.length() && source.charAt(position) == ')') {
                    position++;
                }
                return inner;
            }
            if (Character.isDigit(c)) {
                int start = position;
                while (position < source.length()
                    && (Character.isDigit(source.charAt(position)) || source.charAt(position) == '.')) {
                    position++;
                }
                return source.substring(start, position);
            }
            if (Character.isLetter(c) || c == '_') {
                int start = position;
                while (position < source.length()
                    && (Character.isLetterOrDigit(source.charAt(position)) || source.charAt(position) == '_')) {
                    position++;
                }
                String identifier = source.substring(start, position);
                skipWhitespace();
                if (position < source.length() && source.charAt(position) == '(') {
                    position++;
                    StringBuilder call = new StringBuilder("(").append(identifier);
                    while (true) {
                        String arg = parseExpression();
                        call.append(' ').append(arg);
                        skipWhitespace();
                        if (position < source.length() && source.charAt(position) == ',') {
                            position++;
                            continue;
                        }
                        break;
                    }
                    if (position < source.length() && source.charAt(position) == ')') {
                        position++;
                    }
                    call.append(')');
                    return call.toString();
                }
                return identifier;
            }
            position++;
            return Character.toString(c);
        }

        private void skipWhitespace() {
            while (position < source.length() && Character.isWhitespace(source.charAt(position))) {
                position++;
            }
        }
    }
}
