package de.regelsuche.transform;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Deterministic bounded cache for polynomial macros already generated by an
 * exact theory method.
 *
 * <p>The cache is deliberately separate from the kernel and standard rule
 * inventory. A distinct mathematical macro occupies one capacity slot while
 * independently content-addressed lineages retain primitive expansion and
 * source provenance. Eviction is deterministic insertion-order FIFO. A cache
 * miss carries no mathematical meaning.</p>
 */
public final class PolynomialDerivedMacroCache {
    public static final int DEFAULT_CAPACITY = 128;
    public static final String SCHEMA =
        "regelsuche.polynomial-derived-macro-cache-entry/v1";
    public static final String PURPOSE =
        "PERFORMANCE_CACHE_FOR_THEORY_DERIVED_POLYNOMIAL_MACROS";

    private final int capacity;
    private final Map<String, Entry> entries = new LinkedHashMap<>();

    public PolynomialDerivedMacroCache() {
        this(DEFAULT_CAPACITY);
    }

    public PolynomialDerivedMacroCache(int capacity) {
        if (capacity < 1) {
            throw new IllegalArgumentException(
                "derived macro cache capacity must be positive");
        }
        this.capacity = capacity;
    }

    public synchronized Entry retain(
        PolynomialTheorySubsumptionClassifier.Classification classification,
        List<String> primitiveRuleIds,
        List<String> sourceProvenance
    ) {
        Objects.requireNonNull(classification, "classification");
        if (!classification.subsumed()
                || classification.retentionDisposition()
                    != PolynomialTheorySubsumptionClassifier
                        .RetentionDisposition.DERIVED_MACRO_CACHE_ONLY) {
            throw new IllegalArgumentException(
                "only exactly theory-subsumed identities may enter the cache");
        }

        Lineage lineage = Lineage.create(
            primitiveRuleIds,
            sourceProvenance);
        String id = entryId(classification);
        Entry existing = entries.get(id);
        if (existing != null) {
            Entry updated = existing.withLineage(lineage);
            entries.put(id, updated);
            return updated;
        }

        Entry retained = new Entry(
            id,
            classification.sourceExpression(),
            classification.derivedExpression(),
            classification,
            List.of(lineage),
            PURPOSE);
        entries.put(id, retained);
        evictToCapacity();
        return retained;
    }

    public synchronized Optional<Entry> find(String id) {
        return Optional.ofNullable(entries.get(id));
    }

    public synchronized List<Entry> entries() {
        return List.copyOf(entries.values());
    }

    public synchronized int size() {
        return entries.size();
    }

    public int capacity() {
        return capacity;
    }

    private void evictToCapacity() {
        while (entries.size() > capacity) {
            String oldest = entries.keySet().iterator().next();
            entries.remove(oldest);
        }
    }

    private static String entryId(
        PolynomialTheorySubsumptionClassifier.Classification classification
    ) {
        StringBuilder material = new StringBuilder();
        append(material, SCHEMA);
        append(material, PURPOSE);
        append(material, classification.sourceExpression());
        append(material, classification.derivedExpression());
        append(material, classification.theoryMethodId());
        append(material, classification.certificateHash());
        return sha256(material.toString());
    }

    private static void append(StringBuilder target, String value) {
        target.append(value.length()).append(':').append(value);
    }

    private static List<String> requireNonBlankList(
        List<String> values,
        String name
    ) {
        Objects.requireNonNull(values, name);
        if (values.isEmpty()) {
            throw new IllegalArgumentException(name + " must not be empty");
        }
        List<String> copy = new ArrayList<>(values.size());
        for (String value : values) {
            requireText(value, name + " entry");
            copy.add(value);
        }
        return List.copyOf(copy);
    }

    private static void requireText(String value, String name) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " must not be blank");
        }
    }

    private static String sha256(String material) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256")
                .digest(material.getBytes(StandardCharsets.UTF_8));
            return "sha256:" + HexFormat.of().formatHex(digest);
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 unavailable", exception);
        }
    }

    public record Entry(
        String id,
        String leftPattern,
        String rightPattern,
        PolynomialTheorySubsumptionClassifier.Classification classification,
        List<Lineage> lineages,
        String purpose
    ) {
        public Entry {
            if (id == null || !id.matches("sha256:[0-9a-f]{64}")
                    || leftPattern == null || leftPattern.isBlank()
                    || rightPattern == null || rightPattern.isBlank()
                    || classification == null || !classification.subsumed()
                    || !leftPattern.equals(classification.sourceExpression())
                    || !rightPattern.equals(classification.derivedExpression())
                    || purpose == null || !PURPOSE.equals(purpose)) {
                throw new IllegalArgumentException(
                    "derived polynomial macro cache entry is invalid");
            }
            lineages = List.copyOf(lineages);
            if (lineages.isEmpty()) {
                throw new IllegalArgumentException(
                    "derived polynomial macro requires at least one lineage");
            }
        }

        private Entry withLineage(Lineage lineage) {
            if (lineages.stream().anyMatch(existing ->
                    existing.id().equals(lineage.id()))) {
                return this;
            }
            List<Lineage> updated = new ArrayList<>(lineages);
            updated.add(lineage);
            return new Entry(
                id,
                leftPattern,
                rightPattern,
                classification,
                updated,
                purpose);
        }
    }

    public record Lineage(
        String id,
        List<String> primitiveRuleIds,
        List<String> sourceProvenance
    ) {
        public Lineage {
            if (id == null || !id.matches("sha256:[0-9a-f]{64}")) {
                throw new IllegalArgumentException(
                    "derived polynomial macro lineage id is invalid");
            }
            primitiveRuleIds = requireNonBlankList(
                primitiveRuleIds,
                "primitiveRuleIds");
            sourceProvenance = requireNonBlankList(
                sourceProvenance,
                "sourceProvenance");
        }

        private static Lineage create(
            List<String> primitiveRuleIds,
            List<String> sourceProvenance
        ) {
            List<String> primitives = requireNonBlankList(
                primitiveRuleIds,
                "primitiveRuleIds");
            List<String> provenance = requireNonBlankList(
                sourceProvenance,
                "sourceProvenance");
            StringBuilder material = new StringBuilder();
            append(material, SCHEMA + ".lineage");
            append(material, Integer.toString(primitives.size()));
            primitives.forEach(value -> append(material, value));
            append(material, Integer.toString(provenance.size()));
            provenance.forEach(value -> append(material, value));
            return new Lineage(
                sha256(material.toString()),
                primitives,
                provenance);
        }
    }
}
