package de.regelsuche.discovery.representation;

public enum RepresentationAssessmentWarning {
    INTRODUCED_VARIABLE_SYMBOLS,
    INTRODUCED_FUNCTION_SYMBOLS,
    STRUCTURAL_COMPRESSION_REGRESSION,
    KNOWN_FORM_WITHOUT_NEW_CAPABILITY,
    UNSATISFIED_KNOWN_STRUCTURE_ASSUMPTIONS,
    VALIDATION_BELOW_SYMBOLIC_CONFIRMATION
}
