package de.regelsuche.release;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.github.dockerjava.api.model.Capability;
import com.github.dockerjava.api.model.HostConfig;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFileAttributeView;
import java.nio.file.attribute.PosixFilePermissions;
import java.time.Duration;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.testcontainers.containers.BindMode;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.startupcheck.OneShotStartupCheckStrategy;
import org.testcontainers.images.builder.ImageFromDockerfile;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * Executes the public independent-reproduction image contract through
 * Testcontainers from an ordinary checkout.
 *
 * <p>The artifact directory is generated by the root Gradle lifecycle before
 * this test starts. The evaluated run has no network, drops every Linux
 * capability, enables no-new-privileges and retains a bounded PID allowance.
 * GitHub Actions is not involved in the pass/fail semantics.</p>
 */
@Testcontainers(disabledWithoutDocker = true)
class IndependentReproductionContainerTest {
    private static final Path ARTIFACT_ROOT = Path.of(System.getProperty(
        "regelsuche.independentReproductionArtifactRoot"
    )).toAbsolutePath().normalize();
    private static final String SOURCE_REVISION = System.getProperty(
        "regelsuche.independentReproductionSourceRevision"
    );
    private static final String ARCHITECTURE = System.getProperty(
        "regelsuche.independentReproductionArchitecture",
        "linux/amd64"
    );

    @Test
    void publicArtifactImageReproducesExpectedEvidenceWithoutNetwork(
        @TempDir Path temporaryDirectory
    ) throws Exception {
        assertTrue(Files.isDirectory(ARTIFACT_ROOT), ARTIFACT_ROOT.toString());
        assertTrue(
            SOURCE_REVISION != null && SOURCE_REVISION.matches("[0-9a-f]{40}"),
            "source revision must be an exact Git commit"
        );
        Path dockerfile = ARTIFACT_ROOT.resolve(
            "environment/Dockerfile.reproduction"
        );
        Path expected = ARTIFACT_ROOT.resolve("expected");
        assertTrue(Files.isRegularFile(dockerfile), dockerfile.toString());
        assertTrue(Files.isDirectory(expected), expected.toString());

        Path observed = temporaryDirectory.resolve("observed");
        Files.createDirectories(observed);
        makeContainerWritable(observed);

        ImageFromDockerfile image = new ImageFromDockerfile()
            .withFileFromPath(".", ARTIFACT_ROOT)
            .withDockerfilePath("./environment/Dockerfile.reproduction")
            .withTarget("independent-reproduction")
            .withBuildArg("REGELSUCHE_REPOSITORY_REVISION", SOURCE_REVISION)
            .withBuildImageCmdModifier(command -> command.withPlatform(ARCHITECTURE));

        try {
            GenericContainer<?> container = new GenericContainer<>(image)
                .withFileSystemBind(
                    observed.toString(),
                    "/out",
                    BindMode.READ_WRITE
                )
                .withNetworkMode("none")
                .withCreateContainerCmdModifier(command -> {
                    HostConfig hostConfig = command.getHostConfig();
                    if (hostConfig == null) {
                        hostConfig = HostConfig.newHostConfig();
                    }
                    hostConfig
                        .withCapDrop(Capability.values())
                        .withSecurityOpts(List.of("no-new-privileges"))
                        .withPidsLimit(2048L);
                    command.withHostConfig(hostConfig).withPlatform(ARCHITECTURE);
                })
                .withStartupCheckStrategy(
                    new OneShotStartupCheckStrategy()
                        .withTimeout(Duration.ofMinutes(30))
                )
                .withLogConsumer(frame -> System.err.print(frame.getUtf8String()));
            try {
                container.start();
                HostConfig actual = container.getContainerInfo().getHostConfig();
                assertNotNull(actual, "container host configuration must be inspectable");
                assertEquals("none", actual.getNetworkMode(),
                    "evaluated reproduction run must have no network");
                assertEquals(2048L, actual.getPidsLimit(),
                    "evaluated reproduction run must retain the declared PID bound");
                assertTrue(
                    actual.getSecurityOpts() != null
                        && actual.getSecurityOpts().contains("no-new-privileges"),
                    "evaluated reproduction run must enable no-new-privileges"
                );
                assertTrue(
                    actual.getCapDrop() != null
                        && Arrays.asList(actual.getCapDrop())
                            .containsAll(Arrays.asList(Capability.values())),
                    "evaluated reproduction run must drop every declared capability"
                );
            } finally {
                container.stop();
            }

            assertTreesEqual(expected, observed);
        } finally {
            makeContainerTreeWritable(image, observed);
        }
    }

    private static void makeContainerWritable(Path directory) throws Exception {
        PosixFileAttributeView posix = Files.getFileAttributeView(
            directory,
            PosixFileAttributeView.class
        );
        if (posix != null) {
            posix.setPermissions(PosixFilePermissions.fromString("rwxrwxrwx"));
            return;
        }

        File file = directory.toFile();
        assertTrue(file.setReadable(true, false),
            () -> "could not make bind mount readable: " + directory);
        assertTrue(file.setWritable(true, false),
            () -> "could not make bind mount writable: " + directory);
        assertTrue(file.setExecutable(true, false),
            () -> "could not make bind mount searchable: " + directory);
    }

    private static void makeContainerTreeWritable(
        ImageFromDockerfile image,
        Path directory
    ) {
        if (!Files.exists(directory)) {
            return;
        }
        GenericContainer<?> cleanup = new GenericContainer<>(image)
            .withFileSystemBind(directory.toString(), "/out", BindMode.READ_WRITE)
            .withNetworkMode("none")
            .withCreateContainerCmdModifier(command -> {
                command.withEntrypoint("/bin/sh", "-c");
                command.withCmd("chmod -R a+rwX /out");
            })
            .withStartupCheckStrategy(
                new OneShotStartupCheckStrategy().withTimeout(Duration.ofMinutes(2))
            );
        try {
            cleanup.start();
        } finally {
            cleanup.stop();
        }
    }

    private static void assertTreesEqual(Path expectedRoot, Path actualRoot)
            throws Exception {
        List<Path> expected = regularFiles(expectedRoot);
        List<Path> actual = regularFiles(actualRoot);
        assertEquals(expected, actual, "reproduced file tree differs");
        for (Path relative : expected) {
            assertArrayEquals(
                Files.readAllBytes(expectedRoot.resolve(relative)),
                Files.readAllBytes(actualRoot.resolve(relative)),
                relative.toString()
            );
        }
    }

    private static List<Path> regularFiles(Path root) throws Exception {
        try (var paths = Files.walk(root)) {
            return paths
                .filter(Files::isRegularFile)
                .map(root::relativize)
                .sorted(Comparator.comparing(Path::toString))
                .toList();
        }
    }
}
