package de.regelsuche.docs;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import de.regelsuche.util.AtomicJsonFile;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Runner that generates {@code SearchSpacePowerReport} artifacts for selected discovery scenarios.
 *
 * <p>Scenarios are chosen from the existing public scenario set.  For each scenario the runner:</p>
 * <ol>
 *   <li>Executes the {@link DiscoveryBenchmarkExecutor} to collect full search evidence.</li>
 *   <li>Writes per-scenario artifacts: {@code search-space-power.json}, {@code search-space-power.md},
 *       {@code search-space-power.svg}.</li>
 *   <li>Writes an aggregate index and combined Markdown summary.</li>
 * </ol>
 *
 * <p>Run via the Gradle task {@code runSearchSpacePowerReport} or {@code main()}.</p>
 */
public final class SearchSpacePowerRunner {

    private static final ObjectMapper JSON = new ObjectMapper()
            .findAndRegisterModules()
            .configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);

    private static final List<String> SCENARIO_IDS =
            List.of("complete-square-factorization", "sophie-germain");

    private final DiscoveryBenchmarkScenarioLoader loader = new DiscoveryBenchmarkScenarioLoader();
    private final DiscoveryBenchmarkExecutor executor = new DiscoveryBenchmarkExecutor();
    private final SearchSpacePowerReportWriter writer = new SearchSpacePowerReportWriter();

    public static void main(String[] args) {
        Path repoRoot = args.length == 0
                ? Path.of(".").toAbsolutePath().normalize()
                : Path.of(args[0]).toAbsolutePath().normalize();
        new SearchSpacePowerRunner()
                .writeReport(repoRoot.resolve("app/build/reports/search-space-power"));
    }

    /** Runs the power report for all configured scenarios and returns the aggregate report. */
    public PowerReport run() {
        List<ScenarioResult> results = new ArrayList<>();
        for (DiscoveryBenchmarkScenario scenario : loader.loadAll("discovery-scenarios")) {
            if (!SCENARIO_IDS.contains(scenario.id())) {
                continue;
            }
            DiscoveryBenchmarkEvidence evidence = executor.execute(scenario);
            SearchSpacePowerReport report = SearchSpacePowerReport.compute(evidence);
            results.add(new ScenarioResult(scenario.id(), report));
        }
        results.sort((a, b) -> Integer.compare(
                SCENARIO_IDS.indexOf(a.scenarioId()),
                SCENARIO_IDS.indexOf(b.scenarioId())));
        return new PowerReport("search-space-power", results);
    }

    /** Runs and writes all artifacts to the given output directory. */
    public PowerReport writeReport(Path outputDirectory) {
        try {
            Files.createDirectories(outputDirectory);
            PowerReport aggregate = run();

            for (ScenarioResult result : aggregate.results()) {
                Path scenarioDir = outputDirectory.resolve(slugFor(result.scenarioId()));
                Files.createDirectories(scenarioDir);
                DiscoveryBenchmarkEvidence evidence = executor.execute(
                        loader.loadAll("discovery-scenarios").stream()
                                .filter(s -> s.id().equals(result.scenarioId()))
                                .findFirst()
                                .orElseThrow(() -> new IllegalStateException(
                                        "Missing scenario: " + result.scenarioId())));
                writer.write(scenarioDir, evidence);
            }

            AtomicJsonFile.writeUtf8(
                    outputDirectory.resolve("search-space-power-index.json"),
                    JSON.writerWithDefaultPrettyPrinter().writeValueAsString(aggregate));
            Files.writeString(
                    outputDirectory.resolve("search-space-power.md"),
                    renderAggregateSummary(aggregate),
                    StandardCharsets.UTF_8);
            return aggregate;
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }

    private String renderAggregateSummary(PowerReport aggregate) {
        StringBuilder out = new StringBuilder();
        out.append("# Search-space power: aggregate summary\n\n");
        out.append("> Generated by `SearchSpacePowerRunner`.\n\n");
        out.append("| Scenario | Path length | Max depth | Nodes | Edges | States explored | Canonical states | Pruning | Dead ends |\n");
        out.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: |\n");
        for (ScenarioResult result : aggregate.results()) {
            SearchSpacePowerReport r = result.report();
            out.append("| `").append(escape(r.scenarioId())).append("` | ")
                    .append(r.selectedPathLength()).append(" | ")
                    .append(r.maxExploredDepth()).append(" | ")
                    .append(r.nodeCount()).append(" | ")
                    .append(r.edgeCount()).append(" | ")
                    .append(r.statesExplored()).append(" | ")
                    .append(r.uniqueCanonicalStates()).append(" | ")
                    .append(String.format(Locale.ROOT, "%.1f%%", r.pruningRatio() * 100)).append(" | ")
                    .append(r.deadEndCount()).append(" |\n");
        }
        out.append("\n");

        for (ScenarioResult result : aggregate.results()) {
            out.append("## ").append(escape(result.scenarioId())).append("\n\n");
            out.append("See [search-space-power.md](").append(slugFor(result.scenarioId()))
                    .append("/search-space-power.md) and ")
                    .append("[search-space-power.svg](").append(slugFor(result.scenarioId()))
                    .append("/search-space-power.svg).\n\n");
        }
        return out.toString();
    }

    private String escape(String value) {
        return value == null ? "" : value.replace("|", "\\|");
    }

    private String slugFor(String scenarioId) {
        return scenarioId == null ? "unknown"
                : scenarioId.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9-]", "-");
    }

    public record PowerReport(String id, List<ScenarioResult> results) {
        public PowerReport {
            results = results == null ? List.of() : List.copyOf(results);
        }
    }

    public record ScenarioResult(String scenarioId, SearchSpacePowerReport report) {
    }
}
