package de.regelsuche.docs;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import de.regelsuche.util.AtomicJsonFile;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Writes {@link SearchSpacePowerReport} artifacts:
 * <ul>
 *   <li>{@code search-space-power.json} — full report as JSON</li>
 *   <li>{@code search-space-power.md}   — human-readable Markdown summary</li>
 *   <li>{@code search-space-power.svg}  — depth-histogram SVG visualisation</li>
 * </ul>
 */
public final class SearchSpacePowerReportWriter {

    private static final ObjectMapper JSON = new ObjectMapper()
            .findAndRegisterModules()
            .configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);

    /** Writes all three artifacts and returns the generated report. */
    public SearchSpacePowerReport write(
            Path outputDirectory,
            DiscoveryBenchmarkEvidence evidence) throws IOException {
        Files.createDirectories(outputDirectory);
        SearchSpacePowerReport report = SearchSpacePowerReport.compute(evidence);
        return write(outputDirectory, report);
    }

    /** Writes all three artifacts for an already computed report. */
    public SearchSpacePowerReport write(
            Path outputDirectory,
            SearchSpacePowerReport report) throws IOException {
        Files.createDirectories(outputDirectory);
        AtomicJsonFile.writeUtf8(
                outputDirectory.resolve("search-space-power.json"),
                JSON.writerWithDefaultPrettyPrinter().writeValueAsString(report));
        Files.writeString(
                outputDirectory.resolve("search-space-power.md"),
                renderMarkdown(report),
                StandardCharsets.UTF_8);
        Files.writeString(
                outputDirectory.resolve("search-space-power.svg"),
                renderSvg(report),
                StandardCharsets.UTF_8);
        return report;
    }

    // ── Markdown ──────────────────────────────────────────────────────────────

    String renderMarkdown(SearchSpacePowerReport report) {
        StringBuilder out = new StringBuilder();
        out.append("# Search-space power report: `").append(escape(report.scenarioId())).append("`\n\n");
        out.append("> Generated by `SearchSpacePowerReportWriter`. Do not edit manually.\n\n");

        out.append("## Scenario\n\n");
        out.append("| Field | Value |\n");
        out.append("| --- | --- |\n");
        out.append("| Scenario ID | `").append(escape(report.scenarioId())).append("` |\n");
        out.append("| Input | `").append(escape(report.inputExpression())).append("` |\n");
        out.append("| Target | `").append(escape(report.targetExpression())).append("` |\n\n");

        out.append("## Search-space summary\n\n");
        out.append("The selected path has **").append(report.selectedPathLength())
                .append("** transformation(s), but the search explored **")
                .append(report.statesExplored())
                .append("** generated states, collapsed them to **")
                .append(report.uniqueCanonicalStates())
                .append("** canonical states (pruning ratio: **")
                .append(String.format(Locale.ROOT, "%.2f%%", report.pruningRatio() * 100))
                .append("**), and isolated one target-reaching path.\n\n");

        out.append("| Metric | Value |\n");
        out.append("| --- | ---: |\n");
        out.append("| Selected path length | ").append(report.selectedPathLength()).append(" |\n");
        out.append("| Max explored depth | ").append(report.maxExploredDepth()).append(" |\n");
        out.append("| Node count | ").append(report.nodeCount()).append(" |\n");
        out.append("| Edge count | ").append(report.edgeCount()).append(" |\n");
        out.append("| States explored | ").append(report.statesExplored()).append(" |\n");
        out.append("| Unique canonical states | ").append(report.uniqueCanonicalStates()).append(" |\n");
        out.append("| Estimated pruning ratio | ")
                .append(String.format(Locale.ROOT, "%.2f%%", report.pruningRatio() * 100))
                .append(" |\n");
        out.append("| Dead-end count | ").append(report.deadEndCount()).append(" |\n\n");

        out.append("## Selected path vs alternatives\n\n");
        out.append("| Segment | Nodes | Edges |\n");
        out.append("| --- | ---: | ---: |\n");
        out.append("| Selected path | ").append(report.selectedPathNodeCount())
                .append(" | ").append(report.selectedPathEdgeCount()).append(" |\n");
        out.append("| Alternative branches | ").append(report.alternativeBranchNodeCount())
                .append(" | ").append(report.alternativeBranchEdgeCount()).append(" |\n");
        out.append("| Total | ").append(report.nodeCount())
                .append(" | ").append(report.edgeCount()).append(" |\n\n");

        out.append("## Depth histogram\n\n");
        out.append("| Depth | Node count |\n");
        out.append("| ---: | ---: |\n");
        for (Map.Entry<Integer, Long> entry : report.depthHistogram().entrySet()) {
            out.append("| ").append(entry.getKey()).append(" | ").append(entry.getValue()).append(" |\n");
        }
        out.append("\n");

        out.append("## Edge/source breakdown\n\n");
        out.append("| Source | Edge count |\n");
        out.append("| --- | ---: |\n");
        for (Map.Entry<String, Long> entry : report.edgeSourceBreakdown().entrySet()) {
            out.append("| `").append(escape(entry.getKey())).append("` | ").append(entry.getValue()).append(" |\n");
        }
        out.append("\n");

        out.append("## Edge/kind breakdown\n\n");
        out.append("| Kind | Edge count |\n");
        out.append("| --- | ---: |\n");
        for (Map.Entry<String, Long> entry : report.edgeKindBreakdown().entrySet()) {
            out.append("| `").append(escape(entry.getKey())).append("` | ").append(entry.getValue()).append(" |\n");
        }
        out.append("\n");

        out.append("## Top rule IDs by usage\n\n");
        out.append("| Rule ID | Uses |\n");
        out.append("| --- | ---: |\n");
        for (Map.Entry<String, Long> entry : report.topRuleIds().entrySet()) {
            out.append("| `").append(escape(entry.getKey())).append("` | ").append(entry.getValue()).append(" |\n");
        }
        out.append("\n");

        String telemetrySlug = slugFor(report.scenarioId());
        out.append("## See also\n\n");
        out.append("- [Runtime telemetry summary](../../search-telemetry/").append(telemetrySlug)
                .append("/search-telemetry-summary.md) — per-event counters and rule usage recorded during the search.\n");
        out.append("- [Timeline SVG](../../search-telemetry/").append(telemetrySlug)
                .append("/search-telemetry-timeline.svg) — frontier and visited-count chart over search events.\n");
        out.append("- [Replay](../../search-telemetry/").append(telemetrySlug)
                .append("/search-telemetry-replay.html) — step through individual events interactively.\n");
        out.append('\n');

        return out.toString();
    }

    // ── SVG depth-histogram ───────────────────────────────────────────────────

    String renderSvg(SearchSpacePowerReport report) {
        Map<Integer, Long> histogram = report.depthHistogram();
        List<Map.Entry<Integer, Long>> entries = histogram.entrySet().stream()
                .sorted(Comparator.comparingInt(Map.Entry::getKey))
                .toList();

        long maxCount = entries.stream().mapToLong(Map.Entry::getValue).max().orElse(1);

        int svgWidth = 900;
        int svgHeight = 460;
        int chartLeft = 60;
        int chartRight = svgWidth - 40;
        int chartTop = 60;
        int chartBottom = svgHeight - 100;
        int chartWidth = chartRight - chartLeft;
        int chartHeight = chartBottom - chartTop;

        int barCount = Math.max(1, entries.size());
        int barWidth = Math.max(6, chartWidth / barCount - 4);

        StringBuilder bars = new StringBuilder();
        StringBuilder labels = new StringBuilder();
        for (int i = 0; i < entries.size(); i++) {
            Map.Entry<Integer, Long> entry = entries.get(i);
            int depth = entry.getKey();
            long count = entry.getValue();
            int barH = (int) Math.round((double) count / maxCount * chartHeight);
            int x = chartLeft + i * (chartWidth / barCount) + 2;
            int y = chartBottom - barH;

            bars.append("<rect x=\"").append(x)
                    .append("\" y=\"").append(y)
                    .append("\" width=\"").append(barWidth)
                    .append("\" height=\"").append(barH)
                    .append("\" fill=\"#6366f1\" fill-opacity=\"0.8\" rx=\"2\"><title>depth ")
                    .append(depth).append(": ").append(count).append(" node(s)</title></rect>\n");

            labels.append("<text x=\"").append(x + barWidth / 2)
                    .append("\" y=\"").append(chartBottom + 16)
                    .append("\" font-size=\"10\" text-anchor=\"middle\" fill=\"#334155\">")
                    .append(depth).append("</text>\n");

            if (barH > 14) {
                labels.append("<text x=\"").append(x + barWidth / 2)
                        .append("\" y=\"").append(y - 3)
                        .append("\" font-size=\"9\" text-anchor=\"middle\" fill=\"#334155\">")
                        .append(count).append("</text>\n");
            }
        }

        String pruningLabel = String.format(Locale.ROOT, "%.1f%%", report.pruningRatio() * 100);
        int midY = (chartTop + chartBottom) / 2;
        int xAxisLabelY = chartBottom + 34;
        int maxCountY = chartTop - 8;
        int zeroY = chartBottom - 4;
        int legendY = svgHeight - 20;

        return """
                <svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" data-generated-by="SearchSpacePowerReportWriter" data-scenario-id="${scenarioId}">
                  <rect width="100%" height="100%" fill="#f8fafc"/>
                  <text x="40" y="36" font-size="15" font-weight="700" fill="#1e293b">Search-space depth histogram: ${scenarioId}</text>
                  <text x="40" y="54" font-size="11" fill="#64748b">Selected path: ${pathLen} step(s) · Total nodes: ${nodes} · States explored: ${states} · Unique canonical: ${canonical} · Pruning: ${pruning}</text>
                  <line x1="${chartLeft}" y1="${chartTop}" x2="${chartLeft}" y2="${chartBottom}" stroke="#94a3b8" stroke-width="1.5"/>
                  <line x1="${chartLeft}" y1="${chartBottom}" x2="${chartRight}" y2="${chartBottom}" stroke="#94a3b8" stroke-width="1.5"/>
                  <text x="${chartLeft}" y="${xAxisLabelY}" font-size="11" fill="#64748b" text-anchor="middle">Depth level</text>
                  <text x="14" y="${midY}" font-size="11" fill="#64748b" text-anchor="middle" transform="rotate(-90,14,${midY})">Nodes at depth</text>
                  <text x="${chartLeft}" y="${maxCountY}" font-size="10" fill="#94a3b8">${maxCount}</text>
                  <text x="${chartLeft}" y="${zeroY}" font-size="10" fill="#94a3b8">0</text>
                  ${bars}${labels}
                  <text x="40" y="${legendY}" font-size="11" fill="#475569">
                    Nodes by depth · Selected path: ${pathNodes} nodes, ${pathEdges} edges · Dead ends: ${deadEnds} · Alt branches: ${altNodes} nodes
                  </text>
                </svg>
                """
                .replace("${w}", Integer.toString(svgWidth))
                .replace("${h}", Integer.toString(svgHeight))
                .replace("${scenarioId}", escapeXml(report.scenarioId()))
                .replace("${pathLen}", Integer.toString(report.selectedPathLength()))
                .replace("${nodes}", Integer.toString(report.nodeCount()))
                .replace("${states}", Integer.toString(report.statesExplored()))
                .replace("${canonical}", Integer.toString(report.uniqueCanonicalStates()))
                .replace("${pruning}", escapeXml(pruningLabel))
                .replace("${chartLeft}", Integer.toString(chartLeft))
                .replace("${chartRight}", Integer.toString(chartRight))
                .replace("${chartTop}", Integer.toString(chartTop))
                .replace("${chartBottom}", Integer.toString(chartBottom))
                .replace("${midY}", Integer.toString(midY))
                .replace("${maxCount}", Long.toString(maxCount))
                .replace("${bars}", bars.toString())
                .replace("${labels}", labels.toString())
                .replace("${legendY}", Integer.toString(legendY))
                .replace("${xAxisLabelY}", Integer.toString(xAxisLabelY))
                .replace("${maxCountY}", Integer.toString(maxCountY))
                .replace("${zeroY}", Integer.toString(zeroY))
                .replace("${pathNodes}", Integer.toString(report.selectedPathNodeCount()))
                .replace("${pathEdges}", Integer.toString(report.selectedPathEdgeCount()))
                .replace("${deadEnds}", Integer.toString(report.deadEndCount()))
                .replace("${altNodes}", Integer.toString(report.alternativeBranchNodeCount()));
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String escape(String value) {
        return value == null ? "" : value.replace("\n", " ").replace("\r", " ").replace("|", "\\|");
    }

    private String escapeXml(String text) {
        return text == null ? "" : text
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    private String slugFor(String scenarioId) {
        return scenarioId == null ? "unknown"
                : scenarioId.toLowerCase(java.util.Locale.ROOT).replaceAll("[^a-z0-9-]", "-");
    }
}
