package de.regelsuche.didactic;

import java.util.Objects;

/**
 * Optional hook for an LLM-backed phraser that can rephrase a hint
 * generated by {@link HintGenerator} in a more natural, didactically
 * polished way (spec item 9).
 *
 * <p>The default implementation is {@link NoOpLlmHintPhraser}, which
 * returns the input unchanged. Real implementations (calling an
 * external model) live outside this repository — they only need to
 * implement {@link #rephrase(HintGenerator.Hint, PedagogyProfile)} and
 * may delegate I/O however they like.</p>
 *
 * <p>Implementations must be deterministic for tests: given the same
 * input they should produce the same output. Non-deterministic models
 * should be wrapped (e.g. via caching) before being plugged in here.</p>
 */
@FunctionalInterface
public interface LlmHintPhraser {

    /**
     * @return a possibly-rephrased hint. The returned hint must keep
     *         the original {@link HintGenerator.Hint#strength()} — the
     *         phraser may only change the {@link HintGenerator.Hint#text()}.
     */
    HintGenerator.Hint rephrase(HintGenerator.Hint hint, PedagogyProfile profile);

    /**
     * Default phraser: returns the hint unchanged. Used when no LLM
     * integration is wired in.
     */
    final class NoOpLlmHintPhraser implements LlmHintPhraser {
        @Override
        public HintGenerator.Hint rephrase(HintGenerator.Hint hint, PedagogyProfile profile) {
            Objects.requireNonNull(hint, "hint");
            Objects.requireNonNull(profile, "profile");
            return hint;
        }
    }
}
